"""empty message

Revision ID: 26b7d0f495c5
Revises: 7ba738470860
Create Date: 2016-07-22 02:24:41.975252

"""

# revision identifiers, used by Alembic.
revision = '26b7d0f495c5'
down_revision = '7ba738470860'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('collected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    ### end Alembic commands ###
