"""empty message

Revision ID: 54b962ccf660
Revises: 51a392584118
Create Date: 2016-07-10 02:02:09.319038

"""

# revision identifiers, used by Alembic.
revision = '54b962ccf660'
down_revision = '51a392584118'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    ### end Alembic commands ###
