"""empty message

Revision ID: 60f14fe2996c
Revises: 74f9be75dae5
Create Date: 2016-07-07 01:20:48.258093

"""

# revision identifiers, used by Alembic.
revision = '60f14fe2996c'
down_revision = '74f9be75dae5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('slug', sa.String(length=64), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'projects', ['slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'slug')
    ### end Alembic commands ###
