"""empty message

Revision ID: 7511dda55e85
Revises: None
Create Date: 2016-06-21 20:36:23.314498

"""

# revision identifiers, used by Alembic.
revision = '7511dda55e85'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('url', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'projects', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'url')
    ### end Alembic commands ###
