"""empty message

Revision ID: 7ba738470860
Revises: a46258bbaf10
Create Date: 2016-07-12 19:56:22.623840

"""

# revision identifiers, used by Alembic.
revision = '7ba738470860'
down_revision = 'a46258bbaf10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('tags', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'tags')
    ### end Alembic commands ###
