"""empty message

Revision ID: bbfde928b0ec
Revises: 60f14fe2996c
Create Date: 2016-07-10 01:19:50.284468

"""

# revision identifiers, used by Alembic.
revision = 'bbfde928b0ec'
down_revision = '60f14fe2996c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
