"""empty message

Revision ID: c4018fc490fc
Revises: None
Create Date: 2016-06-28 01:27:50.654112

"""

# revision identifiers, used by Alembic.
revision = 'c4018fc490fc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('modified', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'modified')
    op.drop_column('projects', 'created')
    ### end Alembic commands ###
