"""empty message

Revision ID: cad4b861c6f3
Revises: e7fa899d5912
Create Date: 2016-07-10 02:12:12.213440

"""

# revision identifiers, used by Alembic.
revision = 'cad4b861c6f3'
down_revision = 'e7fa899d5912'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    ### end Alembic commands ###
